Multilevel Deduplication Engine (MDE): mde::MapAdapter< MapClass > Class Template Reference
mde::MapAdapter< MapClass > Class Template Reference
#include <mde.hpp>
Public Types
using Map = MapClass
using Key = typename Map::key_type
using MappedType = typename Map::mapped_type
using KeyValuePair = typename Map::value_type
Public Member Functions
Optional< MappedType > find (const Key &key) const
void insert (KeyValuePair &&v)
void clear ()
Size size () const
Map::const_iterator begin () const
Map::const_iterator end () const
String to_string () const
Protected Attributes
Map data
Detailed Description
template<typename MapClass>
class mde::MapAdapter< MapClass >
Definition at line 776 of file mde.hpp.
Member Typedef Documentation
Key
template<typename MapClass > using mde::MapAdapter< MapClass >::Key = typename Map::key_type
Definition at line 779 of file mde.hpp.
KeyValuePair
template<typename MapClass > using mde::MapAdapter< MapClass >::KeyValuePair = typename Map::value_type
Definition at line 781 of file mde.hpp.
Map
template<typename MapClass > using mde::MapAdapter< MapClass >::Map = MapClass
Definition at line 778 of file mde.hpp.
MappedType
template<typename MapClass > using mde::MapAdapter< MapClass >::MappedType = typename Map::mapped_type
Definition at line 780 of file mde.hpp.
Member Function Documentation
begin()
template<typename MapClass > Map::const_iterator mde::MapAdapter< MapClass >::begin () const inline
Definition at line 813 of file mde.hpp.
clear()
template<typename MapClass > void mde::MapAdapter< MapClass >::clear () inline
Definition at line 803 of file mde.hpp.
Referenced by mde::MDENode< Config, NestingT >::clear().
end()
template<typename MapClass > Map::const_iterator mde::MapAdapter< MapClass >::end () const inline
Definition at line 817 of file mde.hpp.
find()
template<typename MapClass > Optional< MappedType > mde::MapAdapter< MapClass >::find (const Key & key) const inline
Definition at line 788 of file mde.hpp.
Referenced by mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set_single(), and mde::MDENode< Config, NestingT >::register_set_single().
insert()
template<typename MapClass > void mde::MapAdapter< MapClass >::insert (KeyValuePair && v) inline
Definition at line 798 of file mde.hpp.
Referenced by mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set(), mde::MDENode< Config, NestingT >::register_set_single(), and mde::MDENode< Config, NestingT >::register_set_single().
size()
template<typename MapClass > Size mde::MapAdapter< MapClass >::size () const inline
Definition at line 808 of file mde.hpp.
to_string()
template<typename MapClass > String mde::MapAdapter< MapClass >::to_string () const inline
Definition at line 821 of file mde.hpp.
Member Data Documentation
data
template<typename MapClass > Map mde::MapAdapter< MapClass >::data protected
Definition at line 784 of file mde.hpp.
The documentation for this class was generated from the following file:
src/include/mde/mde.hpp