Multilevel Deduplication Engine (MDE): mde::PerformanceStatistics Struct Reference
mde::PerformanceStatistics Struct Reference
Utility class for enabling code-based profiling.
#include <profiling.hpp>
Classes
struct Duration
Public Types
using Count = uint64_t
using String = std::string
using TimePoint = std::chrono::steady_clock::time_point
template<typename K , typename V >
using Map = std::map< K, V >
using Mutex = std::mutex
using WriteLock = std::lock_guard< std::mutex >
using ThreadID = std::thread::id
Public Member Functions
Duration & get_timer (const String &s)
void timer_start (const String &s)
void timer_end (const String &s)
Count & get_counter (const String &s)
void inc_counter (const String &s)
String dump () const
Static Public Member Functions
static const ThreadID currthread ()
Public Attributes
std::mutex mutex
Map< String, Count > counters
Map< ThreadID, Map< String, Duration > > timers
Detailed Description
Utility class for enabling code-based profiling.
Definition at line 24 of file profiling.hpp.
Member Typedef Documentation
Count
using mde::PerformanceStatistics::Count = uint64_t
Definition at line 25 of file profiling.hpp.
Map
template<typename K , typename V > using mde::PerformanceStatistics::Map = std::map<K, V>
Definition at line 28 of file profiling.hpp.
Mutex
using mde::PerformanceStatistics::Mutex = std::mutex
Definition at line 30 of file profiling.hpp.
String
using mde::PerformanceStatistics::String = std::string
Definition at line 26 of file profiling.hpp.
ThreadID
using mde::PerformanceStatistics::ThreadID = std::thread::id
Definition at line 32 of file profiling.hpp.
TimePoint
using mde::PerformanceStatistics::TimePoint = std::chrono::steady_clock::time_point
Definition at line 27 of file profiling.hpp.
WriteLock
using mde::PerformanceStatistics::WriteLock = std::lock_guard<std::mutex>
Definition at line 31 of file profiling.hpp.
Member Function Documentation
currthread()
static const ThreadID mde::PerformanceStatistics::currthread () inline static
Definition at line 57 of file profiling.hpp.
dump()
String mde::PerformanceStatistics::dump () const inline
Definition at line 107 of file profiling.hpp.
Referenced by mde::MDENode< Config, NestingT >::dump_perf().
get_counter()
Count & mde::PerformanceStatistics::get_counter (const String & s) inline
Definition at line 92 of file profiling.hpp.
Referenced by inc_counter().
get_timer()
Duration & mde::PerformanceStatistics::get_timer (const String & s) inline
Definition at line 61 of file profiling.hpp.
Referenced by timer_end(), and timer_start().
inc_counter()
void mde::PerformanceStatistics::inc_counter (const String & s) inline
Definition at line 100 of file profiling.hpp.
timer_end()
void mde::PerformanceStatistics::timer_end (const String & s) inline
Definition at line 81 of file profiling.hpp.
Referenced by mde::__CalcTime::~__CalcTime().
timer_start()
void mde::PerformanceStatistics::timer_start (const String & s) inline
Definition at line 73 of file profiling.hpp.
Referenced by mde::__CalcTime::__CalcTime().
Member Data Documentation
counters
Map<String, Count> mde::PerformanceStatistics::counters
Definition at line 52 of file profiling.hpp.
Referenced by dump(), and get_counter().
mutex
std::mutex mde::PerformanceStatistics::mutex
Definition at line 34 of file profiling.hpp.
Referenced by inc_counter(), timer_end(), and timer_start().
timers
Map<ThreadID, Map<String, Duration> > mde::PerformanceStatistics::timers
Definition at line 53 of file profiling.hpp.
Referenced by dump(), and get_timer().
The documentation for this struct was generated from the following file:
src/include/mde/profiling.hpp